### ISSUE TITLE
As an alumni, be able to edit my  general information such as first name, last name ,  email , gender, phone number, profile image, and cover image.

### ISSUE THREAD

**Issue by Chamsmey** [pnc-virtual-company/2022-G7-VC2-PART2#6]

**Comment by mengyi-dev** [comment]
![Image](https://user-images.githubusercontent.com/90229183/189508518-05aef5f7-fd64-493a-a28d-6432b2ef83b1.svg)

**Comment by mengyi-dev** [comment]
![Image](https://user-images.githubusercontent.com/90229183/189511002-8db5504b-d3e6-4ecf-8d3f-ef1c8d32a8c4.svg)



![Image](https://user-images.githubusercontent.com/90229183/189510478-5573a0fe-932f-49cb-a5a4-8caf9cb3f16e.svg)

**Comment by mengyi-dev** [comment]
![Image](https://user-images.githubusercontent.com/90229183/190053358-f2104099-c05a-4620-b0e2-4fb2617366e2.svg)

Update layout of the name, phone, batch, gener
